spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/ilibarary
    username: postgres
    password: postgres
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: create
credentials:
  client:
  - api-key: 0adf-7c2c-9e37-4378-8161-2d5d-2d88-3a8a
    consumer: consumer-x
    username: username-x
    password: password-x
  - api-key: 6d4d-3dca--f46-8-4f-ff-9-fff--d813-a35c-5896
    consumer: consumer-x
    username: username-x
    password: password-x
  - api-key: ee68-8b97--289-4-49-20-a-4b4--9430-a180-db5e
    consumer: consumer-x
    username: username-x
    password: password-x
  - api-key: 35da-a419--e8e-9-4f-e9-8-c9b--e088-4363-c18a
    consumer: consumer-x
    username: username-x
    password: password-x
  - api-key: ac21-2c34--172-4-44-2a-b-c36--09a1-c52f-d8e7
    consumer: consumer-x
    username: username-x
    password: password-x
  - api-key: 0781-d7e7--632-0-4f-5f-b-431--02f4-8eab-31a4
    consumer: consumer-x
    username: username-x
    password: password-x
