spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/ilibarary
    username: postgres
    password: postgres
    driver-class-name: org.postgresql.Driver
credentials:
  client:
  - api-key: 0adf-7c2c-9e37-4378-8161-2d5d-2d88-3a8a
    consumer: consumer-x
    username: username-x
    password: password-x
  - api-key: 0363-e6ff-ff6a-4983-a9c6-f91e-bb4d-1e42
    consumer: consumer-x
    username: username-x
    password: password-x
  - api-key: c418-02f1-1b39-426c-908b-9f57-6525-48a8
    consumer: consumer-x
    username: username-x
    password: password-x
  - api-key: 392f-179c-d762-4b02-a128-9480-ce5d-da9e
    consumer: consumer-x
    username: username-x
    password: password-x
  - api-key: 1515-7e42--ab9-2-41-27-b-e3d--abcd-2947-544d
    consumer: consumer-x
    username: username-x
    password: password-x
  - api-key: 9545-b6cc--450-2-44-bf-a-960--e92b-2bad-6978
    consumer: consumer-x
    username: username-x
    password: password-x
